### ISSUE TITLE
Parts selection

### ISSUE THREAD

**Issue by jgc128** [jgc128/line-follower-robot#1]
Generally, we need:
- [ ] Wheels+Motors - 2pcs (#2)
- [ ] Ball caster (#3)
- [ ] Brass standoffs (#4)
- [ ] Prototyping board+basis (#5)
- [ ] Batteries, phototransistors, LEDs & other electrical parts like wires (#6)
